### ISSUE TITLE
Fix Timeline Look

### ISSUE THREAD

**Issue by LVOL98** [LVOL98/E-vil-Corp#18]
# Overview

- Correct format of messages
- Load Gravavatar
  - Fix SHA1 in C#

**Comment by LVOL98** [comment]
- [x] Implemented a MD5 hashing algorithm, which could be used later on with password interpretation, see minitwit GravatarUrl
@Abea5

**Comment by Abea5** [comment]
Everything looks great. But on "My Timeline" my messages are only shown if I don't follow anyone - they reapear when I unfollow everyone again. And a very small thing: The text field dosn't clear when clicking share button.
On Public timeline: When I click on a user. It takes me to all that user's messages, but the name of the page is "My Timeline" (tldr: A different user's timeline is still called "My Timeline")
Also a smaller point / question: I can't see the date / time of the messages that aren't my own - only what seems like an ID. Is this intentional? And should we then show it?
